// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:2a1fca7e-b0da-440a-8ebc-e33405d10f4e',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '540b497c4550439490999fc9a5a8b27c',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'cb10d716-36c7-49f5-b2f5-d44df969dcda',
    'aws_project_name': 'potluck-enterprise-apps',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'potluckenterpriseapp-mobilehub-408727706',
    'aws_user_files': 'enable',
    'aws_user_files_s3_bucket': 'potluckenterpriseapp-userfiles-mobilehub-408727706',
    'aws_user_files_s3_bucket_region': 'us-east-1',
}

export default awsmobile;
